// This file is auto-generated by scripts/generate-skills-content.ts.
// Do not edit this file manually.

import type { SkillDefinition } from "./types.js";

export const DEFAULT_SKILLS: SkillDefinition[] = [
  {
    "id": "crm-add-candidate-profile-note",
    "name": "CRM Add Candidate Profile Note",
    "description": "Append a durable note to a mocked CRM candidate profile.",
    "content": "# CRM Add Candidate Profile Note\nDescription: Append a durable note to a mocked CRM candidate profile.\n\nUse this skill when the candidate says something useful for recruiters but it should not overwrite structured profile fields, such as preferences, constraints, context, or follow-up details.\n\nInput contract:\n- `tenantId`: tenant id.\n- `channel`: currently `zalo`.\n- `externalUserId`: Zalo user id.\n- `note`: note text to append.\n- `source`: optional source label.\n\nOutput contract:\n- `profile`: updated candidate profile.\n- `created`: whether a missing profile was created.\n- `note`: appended note metadata.\n\nThis skill is for durable CRM notes. Use Save History for auditable conversation records.",
    "filePath": "src/skills/crm-add-candidate-profile-note/SKILL.md"
  },
  {
    "id": "crm-get-candidate-profile",
    "name": "CRM Get Candidate Profile",
    "description": "Load a mocked CRM candidate/customer profile by Zalo external user id.",
    "content": "# CRM Get Candidate Profile\nDescription: Load a mocked CRM candidate/customer profile by Zalo external user id.\n\nUse this skill early in the conversation to avoid asking for information that is already known.\n\nInput contract:\n- `tenantId`: tenant id.\n- `channel`: currently `zalo`.\n- `externalUserId`: Zalo user id.\n\nOutput contract:\n- Candidate profile with name, contact details, skills, experience, preferences, and notes when available.",
    "filePath": "src/skills/crm-get-candidate-profile/SKILL.md"
  },
  {
    "id": "crm-update-candidate-profile",
    "name": "CRM Update Candidate Profile",
    "description": "Create or update durable CRM candidate profile fields from Zalo chat.",
    "content": "# CRM Update Candidate Profile\nDescription: Create or update durable CRM candidate profile fields from Zalo chat.\n\nUse this skill when the candidate shares stable profile facts such as name, contact details, location, experience, current title, skills, preferred roles, salary expectation, or availability.\n\nInput contract:\n- `tenantId`: tenant id.\n- `channel`: currently `zalo`.\n- `externalUserId`: Zalo user id.\n- `patch`: partial profile fields to update.\n\nPatchable fields:\n- `displayName`\n- `phone`\n- `email`\n- `location`\n- `yearsOfExperience`\n- `currentTitle`\n- `skills`\n- `preferredRoles`\n- `salaryExpectationVnd`\n- `availability`\n\nOutput contract:\n- `profile`: updated candidate profile.\n- `created`: whether a missing profile was created.\n\nThis skill is for durable CRM facts. Use Gather Requirement for temporary job-search criteria.",
    "filePath": "src/skills/crm-update-candidate-profile/SKILL.md"
  },
  {
    "id": "gather-requirement",
    "name": "Gather Requirement",
    "description": "Extract and update the candidate's job-search requirements from Zalo chat text.",
    "content": "# Gather Requirement\nDescription: Extract and update the candidate's job-search requirements from Zalo chat text.\n\nUse this skill whenever the candidate gives information about desired role, salary, location, skills, experience, work mode, language, availability, or constraints. (Note: it automatically parses and converts USD salaries like \"2k\" or \"2000\" into VND).\n\nInput contract:\n- `messages`: recent candidate messages as text.\n- `existingRequirement`: current known requirement fields.\n\nOutput contract:\n- `requirement`: merged candidate requirement.\n- `missingFields`: important fields still missing.\n- `confidence`: low, medium, or high.\n\nThe skill is deterministic and should be called before matching jobs when the latest user message changes job-search criteria.",
    "filePath": "src/skills/gather-requirement/SKILL.md"
  },
  {
    "id": "load-jobs",
    "name": "Load Jobs",
    "description": "Query and filter mocked job postings for HR recruiter conversations.",
    "content": "# Load Jobs\nDescription: Query and filter mocked job postings for HR recruiter conversations.\n\nUse this skill when the candidate has enough requirement details to search jobs, or when the agent needs to explain what opportunities are available.\n\nInput contract:\n- `role`: desired role.\n- `location`: desired location.\n- `workMode`: remote, hybrid, or onsite.\n- `salaryMinVnd`: expected minimum salary in Vietnamese Dong (VND). IMPORTANT: If the candidate gives the salary in USD (e.g. 2k net, 2,000 USD), you MUST convert it to VND by multiplying by 25,000 (e.g. 2000 USD = 50,000,000 VND) before passing it.\n- `skills`: relevant skills.\n\nOutput contract:\n- Matching jobs sorted by rough relevance.\n- `filtersApplied` for transparency.",
    "filePath": "src/skills/load-jobs/SKILL.md"
  },
  {
    "id": "save-history",
    "name": "Save History",
    "description": "Save user, assistant, or tool interaction history in the in-memory DB-shaped store.",
    "content": "# Save History\nDescription: Save user, assistant, or tool interaction history in the in-memory DB-shaped store.\n\nUse this skill whenever important user messages, assistant replies, or tool results should be auditable.\n\nInput contract:\n- `tenantId`: tenant id.\n- `threadId`: Zalo thread id.\n- `entries`: role/content/metadata records.\n\nOutput contract:\n- Count of newly stored and total records for the thread.",
    "filePath": "src/skills/save-history/SKILL.md"
  },
  {
    "id": "save-interaction-intent",
    "name": "Save Interaction Intent",
    "description": "Save the current candidate intent and merged requirement state in memory.",
    "content": "# Save Interaction Intent\nDescription: Save the current candidate intent and merged requirement state in memory.\n\nUse this skill after requirement gathering or job matching changes what the agent believes the candidate wants.\n\nInput contract:\n- `tenantId`: tenant id.\n- `threadId`: Zalo thread id.\n- `intent`: short stable intent label.\n- `requirement`: candidate requirement snapshot.\n\nOutput contract:\n- Saved intent record with update timestamp.",
    "filePath": "src/skills/save-interaction-intent/SKILL.md"
  }
];

export const TWENTY_SKILLS: SkillDefinition[] = [
  {
    "id": "compute-job-matches",
    "name": "Twenty — Compute job matches",
    "description": "Rank `jobPosting` records for a candidate using lightweight heuristics (skills overlap, preferred titles, salary band).",
    "content": "# Twenty — Compute job matches\n\nDescription: Rank `jobPosting` records for a candidate using lightweight heuristics (skills overlap, preferred titles, salary band).\n\nWhen to use:\n\n- Candidate wants “best fit” recommendations beyond keyword filters.",
    "filePath": "src/skills/twenty/compute-job-matches/SKILL.md"
  },
  {
    "id": "get-candidate-profile",
    "name": "Twenty — Get candidate profile",
    "description": "Fetch CRM-backed candidate fields from Twenty `Person` records using the custom `externalUserId` field.",
    "content": "# Twenty — Get candidate profile\n\nDescription: Fetch CRM-backed candidate fields from Twenty `Person` records using the custom `externalUserId` field.\n\nWhen to use:\n\n- Start of conversation or before updating requirements when profile facts might exist in Twenty.\n\nNotes:\n\n- Requires recruiting schema applied (`pnpm --filter @platform/worker twenty:schema`) and optional seed data.",
    "filePath": "src/skills/twenty/get-candidate-profile/SKILL.md"
  },
  {
    "id": "get-recruiting-status",
    "name": "Twenty — Get recruiting status",
    "description": "Return Person-level recruiting pipeline stage from Twenty.",
    "content": "# Twenty — Get recruiting status\n\nDescription: Return Person-level recruiting pipeline stage from Twenty.\n\nWhen to use:\n\n- Candidate asks about status or before proposing next steps.",
    "filePath": "src/skills/twenty/get-recruiting-status/SKILL.md"
  },
  {
    "id": "list-in-progress-applications",
    "name": "Twenty — List in-progress applications",
    "description": "Show job applications that are still moving through hiring stages for this external user id.",
    "content": "# Twenty — List in-progress applications\n\nDescription: Show job applications that are still moving through hiring stages for this external user id.\n\nWhen to use:\n\n- Candidate asks what roles are still open / in interview loops.",
    "filePath": "src/skills/twenty/list-in-progress-applications/SKILL.md"
  },
  {
    "id": "search-jobs",
    "name": "Twenty — Search jobs",
    "description": "Query Twenty job postings with optional filters (search + filter combined).",
    "content": "# Twenty — Search jobs\n\nDescription: Query Twenty job postings with optional filters (search + filter combined).\n\nWhen to use:\n\n- Candidate asks for openings or after enough requirement detail exists.\n\nInput contract:\n- `salaryMinVnd`: expected minimum salary in Vietnamese Dong (VND). IMPORTANT: If the candidate gives the salary in USD (e.g. 2k net, 2,000 USD), you MUST convert it to VND by multiplying by 25,000 (e.g. 2000 USD = 50,000,000 VND) before passing it.",
    "filePath": "src/skills/twenty/search-jobs/SKILL.md"
  }
];
