import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");

const skillsDir = path.join(root, "packages/agent/src/skills");
const outputFile = path.join(root, "packages/agent/src/skills-content.ts");

interface SkillDefinition {
  id: string;
  name: string;
  description: string;
  content: string;
  filePath: string;
}

function firstParagraph(content: string) {
  return content
    .split(/\n\s*\n/)
    .map((part) => part.trim())
    .find((part) => part && !part.startsWith("#"));
}

function parseSkillMarkdown(id: string, filePath: string, content: string): SkillDefinition {
  const title = /^#\s+(.+)$/m.exec(content)?.[1]?.trim() ?? id;
  const description =
    /^Description:\s*(.+)$/m.exec(content)?.[1]?.trim() ??
    firstParagraph(content) ??
    title;

  return {
    id,
    name: title,
    description,
    content: content.trim(),
    filePath,
  };
}

function extractSection(markdown: string, heading: string): string {
  const escapedHeading = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const pattern = new RegExp(`^${escapedHeading}\\n([\\s\\S]*?)(?=\\n---|\\n# )`, "m");
  const match = pattern.exec(markdown);
  if (!match) {
    throw new Error(`Section "${heading}" not found in core-instructions.md`);
  }
  return match[1].trim();
}

async function run() {
  console.log("Generating skills content...");
  
  const defaultSkills: SkillDefinition[] = [];
  const twentySkills: SkillDefinition[] = [];
  
  const entries = await fs.readdir(skillsDir, { withFileTypes: true });
  const SKIP_DIRS = new Set(["global", "twenty", "save-history"]);

  // Load default skills
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (SKIP_DIRS.has(entry.name)) continue;

    const skillId = entry.name;
    const filePath = path.join(skillsDir, skillId, "SKILL.md");
    try {
      const content = await fs.readFile(filePath, "utf-8");
      defaultSkills.push(parseSkillMarkdown(skillId, `src/skills/${skillId}/SKILL.md`, content));
    } catch (err: any) {
      if (err.code !== "ENOENT") throw err;
    }
  }

  // Load twenty skills
  const twentyDir = path.join(skillsDir, "twenty");
  const twentyEntries = await fs.readdir(twentyDir, { withFileTypes: true });
  for (const entry of twentyEntries) {
    if (!entry.isDirectory()) continue;

    const skillId = entry.name;
    const filePath = path.join(twentyDir, skillId, "SKILL.md");
    try {
      const content = await fs.readFile(filePath, "utf-8");
      twentySkills.push(parseSkillMarkdown(skillId, `src/skills/twenty/${skillId}/SKILL.md`, content));
    } catch (err: any) {
      if (err.code !== "ENOENT") throw err;
    }
  }

  defaultSkills.sort((a, b) => a.id.localeCompare(b.id));
  twentySkills.sort((a, b) => a.id.localeCompare(b.id));

  const code = `// This file is auto-generated by scripts/generate-skills-content.ts.
// Do not edit this file manually.

import type { SkillDefinition } from "./types.js";

export const DEFAULT_SKILLS: SkillDefinition[] = ${JSON.stringify(defaultSkills, null, 2)};

export const TWENTY_SKILLS: SkillDefinition[] = ${JSON.stringify(twentySkills, null, 2)};
`;

  await fs.writeFile(outputFile, code, "utf-8");
  console.log(`Generated static skills content successfully at: ${outputFile}`);

  // Generate core instructions prompt file
  const promptMdFile = path.join(root, "packages/agent/src/prompt/core-instructions.md");
  const promptTsFile = path.join(root, "packages/agent/src/prompt/core-instructions.ts");
  try {
    const promptContent = await fs.readFile(promptMdFile, "utf-8");
    const personaExamples = extractSection(promptContent, "# Signature Example Exchanges");
    const promptCode = `// This file is auto-generated by scripts/generate-skills-content.ts.
// Do not edit this file manually.

export const CORE_HR_AGENT_INSTRUCTIONS = ${JSON.stringify(promptContent.trim())};

export const PERSONA_EXAMPLES = ${JSON.stringify(personaExamples)};
`;
    await fs.writeFile(promptTsFile, promptCode, "utf-8");
    console.log(`Generated static core instructions successfully at: ${promptTsFile}`);
  } catch (err) {
    console.error("Failed to generate core instructions", err);
    throw err;
  }
}

run().catch((err) => {
  console.error("Failed to generate skills content", err);
  process.exit(1);
});
