import type { JobPosting } from "../../types.js";

export const mockJobs: JobPosting[] = [
  {
    id: "job-fe-001",
    title: "Frontend Engineer",
    company: "Atlas Product Studio",
    companyIntro: "A premium software studio building high-performance SaaS applications with modern tech stacks.",
    companyBenefits: "Flexible hours, MacBooks provided, competitive healthcare, yearly company trip.",
    companyWorkStyle: "High autonomy, cross-functional teams, focus on speed and quality.",
    locationSlugs: ["ho-chi-minh-city"],
    workMode: "hybrid",
    salaryMinVnd: 35_000_000,
    salaryMaxVnd: 55_000_000,
    seniority: "mid",
    requiredSkills: ["React", "TypeScript", "Next.js"],
    description: "Build customer-facing SaaS workflows with a product engineering team.",
  },
  {
    id: "job-be-001",
    title: "Backend Engineer",
    company: "Northstar HR Cloud",
    companyIntro: "Cloud-native HR platform for scaling enterprises across Southeast Asia.",
    companyBenefits: "Full social insurance, 13th month salary, hybrid support, training budgets.",
    companyWorkStyle: "Collaborative, data-driven decisions, customer-first culture.",
    locationSlugs: ["ha-noi"],
    workMode: "onsite",
    salaryMinVnd: 45_000_000,
    salaryMaxVnd: 70_000_000,
    seniority: "senior",
    requiredSkills: ["Node.js", "NestJS", "PostgreSQL"],
    description: "Own APIs, queue workers, and tenant data workflows.",
  },
  {
    id: "job-ai-001",
    title: "AI Engineer",
    company: "Signal Recruit",
    companyIntro: "AI-driven recruiting intelligence service.",
    companyBenefits: "Remote-first budget, stock options, learning allowance, wellness benefits.",
    companyWorkStyle: "Asynchronous communication, result-oriented, self-directed working style.",
    locationSlugs: ["ho-chi-minh-city"],
    workMode: "remote",
    salaryMinVnd: 55_000_000,
    salaryMaxVnd: 85_000_000,
    seniority: "mid-senior",
    requiredSkills: ["Python", "LLM", "SQL"],
    description: "Prototype AI recruiter workflows and evaluation pipelines.",
  },
];
